### ISSUE TITLE
Frame PCB for FPC Toolhead PCB 

### ISSUE THREAD

**Issue by MagicalFire86** [hartk1213/MISC#11]
hello do you plan to make something like Frame PCB for your mod FPC Toolhead PCB ?? 
https://raw.githubusercontent.com/timmit99/Voron-Hardware/V0-Umbilical/V0-Umbilical/Images/Frame_PCB.png

**Comment by hartk1213** [comment]
yes it is, and no i dont plan on making a frame PCB at this time
