### ISSUE TITLE
Issues with the Voron 2.4 GE5C Z joint BOM

### ISSUE THREAD

**Issue by mathiasm74** [hartk1213/MISC#17]
The BOM for the GE5C Z joint calls for 4x M5x20, but these are two short. Without the belt and "M5x1mm spacer" in place it just about reach the T-nut, but with the washer it's just too short. M5x25 screws do the trick.

The BOM also doesn't mention the 4 extra M3x16 screws that replace the original ones for the belt clip (see arrow in image below), as those are too long.

![image](https://user-images.githubusercontent.com/917776/151450382-b942e469-627e-41be-89b6-249592841c3b.png)

![image](https://user-images.githubusercontent.com/917776/151451308-ba10c657-5d84-4e2a-b151-9d0dc8895f06.png)

**Comment by jakep82** [comment]
A more recent version of this is available on the VoronUsers repository which does call out the M3x12 screws necessary for the belt clip, and the M5x20 screws work fine for me using Igus bearings with the STLs at the link.

<https://github.com/VoronDesign/VoronUsers/tree/master/printer_mods/hartk1213/Voron2.4_GE5C>

**Comment by mathiasm74** [comment]
The problem must be I didn't reprint the thinner belt clamps. With those I'm sure it works. 

Guess this is the best that could be done to adapt existing parts, but this design is flawed really. That single M5 screw really can't both clamp the belt clip and allow for any real movement in the joint. Hope the team will come up with a better solution for the next revision.
