### ISSUE TITLE
Y Endstop Mod "incompatible" with 2.4r2

### ISSUE THREAD

**Issue by GiulianoM** [hartk1213/MISC#21]
Slight issue with the Y Endstop relocation mod, the model is based on the 2.4r1 files and the Z chain mount holes are now different.

The 2.4r1 has two mounting holes for the Z chain mount, the 2.4r2 has one single hole in the middle.

Might be a good time to re-do this mod with the original 2.4r2 files, as the geometry on the parts have also slightly changed.

**Comment by FL140** [comment]
@hartk1213 I think this also can be closed as the file for the v2.4r2 can be found in the Pin Mods directory, also the Readme there now contains the content from the Y Endstop Mod directory.

[a_drive_frame_upper_with_jst_y_endstop_pinned.stl](https://github.com/hartk1213/MISC/blob/main/Voron%20Mods/Voron%202/2.4/Voron2.4_Trident_Pins_Mod/STLs/Gantry/AB_Drive_Units/V2/a_drive_frame_upper_with_jst_y_endstop_pinned.stl)

There are just 2 things to do:
1. Leave a comment in the deprecated Y Endstop Mod readme that the files in that directory are deprecated and that the new version has been merged into the Pins Mod directory.
2. It looks like the modified Readme in the Pins Mod directory contains some comments which shouldn't be there (like a stash comment), right?
