### ISSUE TITLE
Voron2.4_Trident_Pins_Mod

### ISSUE THREAD

**Issue by shalev-d** [hartk1213/MISC#22]
It seems that the CAD files are still 2.4r1, not as stated: "Hartk mod update for 2.4r2 (https://github.com/VoronDesign/VoronUsers/pull/638)"
Is there a forecast to when the 2.4r2 files uploaded?

**Comment by bassco** [comment]
Furthermore, is there an updated seller listing or the seller's name for the outdated link to the rod supplier at [AliExpress](https://www.aliexpress.com/item/1739093502.html)?

**Comment by hartk1213** [comment]
> Furthermore, is there an updated seller listing or the seller's name for the outdated link to the rod supplier at [AliExpress](https://www.aliexpress.com/item/1739093502.html)?

LinkCNC is the seller, there are also a bunch of vendors selling these as well
