### ISSUE TITLE
PCBWay overlapped holes

### ISSUE THREAD

**Issue by jvandervyver** [hartk1213/MISC#23]
Hi

I used your link to create an order of https://github.com/hartk1213/MISC/tree/main/PCBs/Stealthburner_Toolhead_PCB
I've got a lot of electronics experience but I've never ordered PCBs (usually I just etch my own).

I got a response from PCBWay as follows:

> Good day. Thanks for you PCB order#xxxxxxxxxxxx_Gerber_Stealthburner.

> There is an engineering question in your Gerber File. As shown in the attached screenshot,  there are 3 holes are overlopped and sizes are different. Which layer should we use? (drl or dril+1)        

> Please check and advise.

> The lead time will be re-calculated after the EQ is solved.

![https://i.imgur.com/jyTc3HK.png](https://i.imgur.com/jyTc3HK.png)

Any chance you could provide some guidance?

**Comment by hartk1213** [comment]
I can update the Gerbers to fix that

**Comment by hartk1213** [comment]
gerbers have been updated to fix that problem, ill close this issue now thank you for pointing that out
