### ISSUE TITLE
Hartk stealth burner 2piece pcb rev2 wont upload to PcbWay

### ISSUE THREAD

**Issue by Sebbeben** [hartk1213/MISC#30]
hi, i really like your work :)

i was trying to order you 2 piece pcb from PcbWay but they have big problems with the file. what software did you use to make the gerber's? 

keep up the good work :))

Best Regards
Sebastian

**Comment by hartk1213** [comment]
i have uploaded new files if you wanted to try those

**Comment by Sebbeben** [comment]
Thanks 😊 
Thats very good if anyone have the problem I had.
