### ISSUE TITLE
Stealthburner PCB: AUX Connector wrong pinout in Schematic

### ISSUE THREAD

**Issue by MaximeLambrechts** [hartk1213/MISC#36]
On the Schematic_StealthburnerPCB.pdf, the pinout of the AUX connector is inversed compared to the PCB and wiring instructions. 

Pin 1 should be GND.
Pïn 2 is correct.
Pin 3 should be AGND.

Thanks for your work ! :)

**Comment by hartk1213** [comment]
this has now been fixed
