### ISSUE TITLE
Stealthburner PCB + LDO kit instructions has a dangerously misleading diagram

### ISSUE THREAD

**Issue by theninj4** [hartk1213/MISC#39]
In the diagram here:
![](https://raw.githubusercontent.com/hartk1213/MISC/main/PCBs/Stealthburner_Toolhead_PCB/Images/LDO/Octopus_CT_5V.png)
The picture suggests one should add the 5v jumper, but also clearly shows the 24v present too.

Having just blown an Octopus and Pi by following the instructions rather than reading the manuals - can I suggest we update the image to indicate that the 24v jumper needs to be **removed**?

**Comment by hartk1213** [comment]
well the information that says you should move it to the 5v jumper is in the write up [here](https://github.com/hartk1213/MISC/tree/main/PCBs/Stealthburner_Toolhead_PCB#ldo-kit-upgrade) in the very first paragraph, i would suggest reading the write along with using the pictures
