### ISSUE TITLE
StealthBurner PCB single board FS port

### ISSUE THREAD

**Issue by appleimperio** [hartk1213/MISC#44]
Why did you use 24v on the filament sensor port when most of the filament sensors are between 3.3v and 5v?

**Comment by Jaans** [comment]
FYI, the ERCF toolhead filament sensor  AH3363Q-P-B works at 24v and is more sensitive at higher voltage.

**Comment by hartk1213** [comment]
there is now a 5v version as well [here](https://github.com/hartk1213/MISC/blob/main/PCBs/Stealthburner_Toolhead_PCB/Production%20Files/StealthburnerPCB/2%20Piece/Gerber_Stealthburner-2PC-Main-5vProbe.zip)
