### ISSUE TITLE
Please add 5v probe to support Voron Tap

### ISSUE THREAD

**Issue by iBral** [hartk1213/MISC#45]
your probe use 24v, new voron tap use 5v, please add 5v support

**Comment by hartk1213** [comment]
already done, there are now files [here](https://github.com/hartk1213/MISC/blob/main/PCBs/Stealthburner_Toolhead_PCB/Production%20Files/StealthburnerPCB/2%20Piece/Gerber_Stealthburner-2PC-Main-5vProbe.zip)
