### ISSUE TITLE
Please provide a 2 or 3 keystone insert variant of your V0.2 rear keystone skirt

### ISSUE THREAD

**Issue by driemekasten** [hartk1213/MISC#49]
Would be nice if we could have a rear keystone skirt for V0.2 with two or three inserts for one or two USB ports.

**Comment by hartk1213** [comment]
https://github.com/hartk1213/MISC/blob/main/Voron%20Mods/Voron%200/0.2/RearKeystoneSkirt/CAD/v02_rear_skirt_keystone.step

cad file is available, you are more than welcome to make one 👍🏻 i wont be making one at this time and im going to close this issue
